/**
 * Downloads the web fonts used by the site and writes a local @font-face
 * stylesheet, so the published site never calls out to Google's CDN.
 *
 * Run with:  npm run fonts
 *
 * Only the `latin` and `latin-ext` subsets are kept — that is everything the
 * site's copy needs, and it keeps the payload small. If you rebrand to fonts
 * that need other subsets, add them to KEEP_SUBSETS below.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const FAMILIES = 'family=Marcellus&family=Jost:wght@300;400;500;600';
const KEEP_SUBSETS = ['latin', 'latin-ext'];
const OUT_DIR = join(process.cwd(), 'src', 'assets', 'fonts');
const OUT_CSS = join(process.cwd(), 'src', 'assets', 'css', 'fonts.css');

// Google serves woff2 only to browser-like user agents.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await fetch(
  `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`,
  { headers: { 'User-Agent': UA } }
).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts CSS returned ${r.status}`);
  return r.text();
});

await mkdir(OUT_DIR, { recursive: true });

// The CSS arrives as `/* subset */ @font-face { ... }` blocks in sequence.
const blocks = css.split('/*').filter((b) => b.includes('@font-face'));
const out = [
  '/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
  "/* Regenerate with `npm run fonts`. */",
  '',
];
let count = 0;

for (const block of blocks) {
  const subset = block.slice(0, block.indexOf('*/')).trim();
  if (!KEEP_SUBSETS.includes(subset)) continue;

  const family = block.match(/font-family:\s*'([^']+)'/)?.[1];
  const weight = block.match(/font-weight:\s*(\d+)/)?.[1] ?? '400';
  const url = block.match(/url\((https:\/\/fonts\.gstatic\.com[^)]+)\)/)?.[1];
  const range = block.match(/unicode-range:\s*([^;]+);/)?.[1];
  if (!family || !url) continue;

  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}-${subset}.woff2`;
  const bytes = await fetch(url, { headers: { 'User-Agent': UA } }).then((r) => {
    if (!r.ok) throw new Error(`${file} returned ${r.status}`);
    return r.arrayBuffer();
  });
  await writeFile(join(OUT_DIR, file), Buffer.from(bytes));
  count += 1;

  out.push(
    '@font-face {',
    `  font-family: '${family}';`,
    '  font-style: normal;',
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url('../fonts/${file}') format('woff2');`,
    ...(range ? [`  unicode-range: ${range};`] : []),
    '}',
    ''
  );
}

await writeFile(OUT_CSS, out.join('\n'));
console.log(`Downloaded ${count} font files -> src/assets/fonts/`);
console.log('Wrote src/assets/css/fonts.css');
